server:
  port: 8081

spring:
  application:
    name: product-service
  config:
    import: "optional:classpath:application.yml"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: jdbc:h2:mem:vendasdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  secret-key: mjJ1QWz22Pr3XpaY9lqsi5iuN5TNuI1S59V+uCsReEM=
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true